### Get JWT Token for OTP code
GET http://localhost/otp/validate/293564

### OTP provisioning
GET http://localhost/otp/provisioning
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI2MDY0N2NhZWYzY2ZlIiwic3ViIjoiNmI2MGRlYWYzOGMyODU2NjRhZjdlODFjZDAxMjJiNTMiLCJpYXQiOjE2MTcxOTgyNTQuOTk4ODc2LCJleHAiOjE2MTk3OTAyNTQuOTk4OTYzfQ.1_BxMqlDegMiC1x4a48rjGM_sOWkAFWl7MJfPTqHbyE
Content-Type: application/json

### GET encode password (password_example) from TOKEN
GET http://localhost/password/add/password_example
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI2MDY0N2NhZWYzY2ZlIiwic3ViIjoiNmI2MGRlYWYzOGMyODU2NjRhZjdlODFjZDAxMjJiNTMiLCJpYXQiOjE2MTcxOTgyNTQuOTk4ODc2LCJleHAiOjE2MTk3OTAyNTQuOTk4OTYzfQ.1_BxMqlDegMiC1x4a48rjGM_sOWkAFWl7MJfPTqHbyE
Content-Type: application/json

### GET all note list
GET http://localhost/def50200d7a0426ab1af5cce28a832154896f4c80a438609c2910f76cc00f8b147a85c7b9fa9e833230bf630fd65dab0fbec7230a06fb005aec5aeec8fb527e0c68bb807a219a5441bc00e19f22c8595fc6f06765f6bb237c964f003554a309378a8f736
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI2MDY0N2NhZWYzY2ZlIiwic3ViIjoiNmI2MGRlYWYzOGMyODU2NjRhZjdlODFjZDAxMjJiNTMiLCJpYXQiOjE2MTcxOTgyNTQuOTk4ODc2LCJleHAiOjE2MTk3OTAyNTQuOTk4OTYzfQ.1_BxMqlDegMiC1x4a48rjGM_sOWkAFWl7MJfPTqHbyE
Content-Type: application/json

### PUSH new note from JSON payload
POST http://localhost/note/add
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI2MDY0N2NhZWYzY2ZlIiwic3ViIjoiNmI2MGRlYWYzOGMyODU2NjRhZjdlODFjZDAxMjJiNTMiLCJpYXQiOjE2MTcxOTgyNTQuOTk4ODc2LCJleHAiOjE2MTk3OTAyNTQuOTk4OTYzfQ.1_BxMqlDegMiC1x4a48rjGM_sOWkAFWl7MJfPTqHbyE
Content-Type: application/json

{
  "password": "def50200d7a0426ab1af5cce28a832154896f4c80a438609c2910f76cc00f8b147a85c7b9fa9e833230bf630fd65dab0fbec7230a06fb005aec5aeec8fb527e0c68bb807a219a5441bc00e19f22c8595fc6f06765f6bb237c964f003554a309378a8f736",
  "name": "Note example",
  "contents": "Note contents"
}

### PUSH new note from form-urlencoded
POST http://localhost/note/add
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI2MDY0N2NhZWYzY2ZlIiwic3ViIjoiNmI2MGRlYWYzOGMyODU2NjRhZjdlODFjZDAxMjJiNTMiLCJpYXQiOjE2MTcxOTgyNTQuOTk4ODc2LCJleHAiOjE2MTk3OTAyNTQuOTk4OTYzfQ.1_BxMqlDegMiC1x4a48rjGM_sOWkAFWl7MJfPTqHbyE
Content-Type: application/x-www-form-urlencoded

password=def50200d7a0426ab1af5cce28a832154896f4c80a438609c2910f76cc00f8b147a85c7b9fa9e833230bf630fd65dab0fbec7230a06fb005aec5aeec8fb527e0c68bb807a219a5441bc00e19f22c8595fc6f06765f6bb237c964f003554a309378a8f736&name=Note example&contents=Note contents

### Delete note by ID
GET http://localhost/note/delete/60647b663ac2e
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI2MDY0N2NhZWYzY2ZlIiwic3ViIjoiNmI2MGRlYWYzOGMyODU2NjRhZjdlODFjZDAxMjJiNTMiLCJpYXQiOjE2MTcxOTgyNTQuOTk4ODc2LCJleHAiOjE2MTk3OTAyNTQuOTk4OTYzfQ.1_BxMqlDegMiC1x4a48rjGM_sOWkAFWl7MJfPTqHbyE
Content-Type: application/json
